name: emrtd
description: "Read and verify electronic passports and ID cards."
version: 0.0.6
homepage: https://kinegram.digital/mobile-chip-sdk/emrtd-connector/
repository: https://github.com/OVD-Kinegram-AG/emrtd-connector-sdk-flutter
issue_tracker: https://github.com/OVD-Kinegram-AG/emrtd-connector-sdk-flutter/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.kurzdigital.emrtd
        pluginClass: EmrtdPlugin
      ios:
        pluginClass: EmrtdPlugin
